cats_version:   v5.7.0
api:            (( grab $API_URL ))
admin_user:     admin
admin_password: (( grab $ADMIN_PASSWORD ))
apps_domain:    (( grab $APP_DOMAINS_0 ))
artifacts_directory: logs

#INCREASE TIMEOUTS AS NEEDED.
default_timeout: 300
cf_push_timeout: 300
detect_timeout: 300
sleep_timeout: 300
broker_start_timeout: 300
long_curl_timeout: 300
async_service_operation_timeout: 300
timeout_scale: 2

stacks:
- cflinuxfs3

use_http: true
use_log_cache: false
skip_ssl_validation: true

# Categorization based on
# https://www.cloudfoundry.org/trainings/demystifying-cf-acceptance-tests/
# https://youtu.be/Gz7UpLw7OTo?t=694
# Current list of supported suits:
# https://github.com/cloudfoundry/cf-acceptance-tests/blob/master/helpers/config/config_struct.go#L69-L93

# Default
include_apps: false
include_detect: false
include_routing: false

# GA Features
include_backend_compatibility: false
include_docker: false # feature flag: diego_docker
include_internet_dependent: false
include_private_docker_registry: false # TODO setup private registry to enable this suite
include_route_services: false
include_security_groups: false
include_services: false #no service brokers deployed
include_ssh: false
include_sso: false
include_tasks: false
include_v3: false
# Could be disabled with cc.temporary_disable_deployments
# but default to false: https://github.com/cloudfoundry/capi-release/blob/master/jobs/cloud_controller_ng/spec#L364
include_deployments: false
include_tcp_routing: false # Not in kit
# enable-service-discovery.yml is being tested by cf-deployment ci
include_service_discovery: false
include_service_instance_sharing: false # feature flag: service_instance_sharing
# https://github.com/cloudfoundry/cf-deployment/commit/8ab94e7a36b197ada2a6992a6e5780b710eb07bd
include_capi_no_bridge: false

# Special Deployment
include_isolation_segments: false
include_routing_isolation_segments: false
include_container_networking: false
credhub_mode: skip
include_zipkin: false
include_volume_services: false

# Misc
include_internetless: false
