releases:
  - name:    bpm
    version: "1.1.6"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=" releases.bpm.version ))
    sha1:    5bad6161dbbcf068830a100b6a76056fe3b99bc8

  - name:    capi
    version: "1.89.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/capi-release?v=" releases.capi.version ))
    sha1:    472966da017bda3118eb9cf71f9bcca1c23c344a

  - name:    cf-networking
    version: "2.27.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cf-networking-release?v=" releases.cf-networking.version ))
    sha1:    1249e8140449126a9eb6102218c89eb1196c649e

  - name:    cf-smoke-tests
    version: "40.0.125"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cf-smoke-tests-release?v=" releases.cf-smoke-tests.version ))
    sha1:    9d1823d9276aba11261ca59e04e96655e418681b

  - name:    cflinuxfs3
    version: "0.154.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cflinuxfs3-release?v=" releases.cflinuxfs3.version ))
    sha1:    ca95b338896f52e8df54c69e7353894ba635c9fd

  - name:    cf-cli
    version: "1.24.0"
    url:     (( concat "https://bosh.io/d/github.com/bosh-packages/cf-cli-release?v=" releases.cf-cli.version ))
    sha1:    2abe6917b9f576a700418522f1bf452af5768819

  - name:    diego
    version: "2.42.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/diego-release?v=" releases.diego.version ))
    sha1:    d92d29385f7b1020d95cdcd12d97e378773d1168

  - name:    garden-runc
    version: "1.19.9"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=" releases.garden-runc.version ))
    sha1:    1c678e1c7a3506c0e408860571560081c15e3c6d

  - name:    loggregator
    version: "106.3.5"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/loggregator-release?v=" releases.loggregator.version ))
    sha1:    d7f5203522753ed9cc12e4c0b5714264d7c37c41

  - name:    loggregator-agent
    version: "5.3.4"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/loggregator-agent-release?v=" releases.loggregator-agent.version ))
    sha1:    d62dd7a540210727ac503cc3856722b78184080b

  - name:    log-cache
    version: "2.6.8"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/log-cache-release?v=" releases.log-cache.version ))
    sha1:    3a5bcd3162387cd2fd2deb6e15a29bfff398cdae

  - name:    nats
    version: "32"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/nats-release?v=" releases.nats.version ))
    sha1:    9cc4979e2d1e7452f8e2b90c6f52d473b080596b

  - name:    routing
    version: "0.196.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/routing-release?v=" releases.routing.version ))
    sha1:    5eab0c9c35b4f047ff83d0a266223edb357cb02d

  - name:    statsd-injector
    version: "1.11.13"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/statsd-injector-release?v=" releases.statsd-injector.version ))
    sha1:    b780e2269e28b62d2306c14fa1c97b914dad7387

  - name:    cf-syslog-drain
    version: "10.2.9"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cf-syslog-drain-release?v=" releases.cf-syslog-drain.version ))
    sha1:    98a18dcff81a983c95b8ce5c0a41b5627f4314ac

  - name:    "uaa"
    version: "75.13.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=" releases.uaa.version ))
    sha1:    "63750fa3fde9e8a325efc1edd613da58bb92a85b"

  - name:    silk
    version: "2.27.0"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/silk-release?v=" releases.silk.version ))
    sha1:    8c3a88affb84cbc28bf659292819c8c0ad23abe7

  - name:    bosh-dns-aliases
    version: "0.0.3"
    url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=" releases.bosh-dns-aliases.version ))
    sha1:    b0d0a0350ed87f1ded58b2ebb469acea0e026ccc
